{"nbformat":4,"nbformat_minor":5,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.8"},"colab":{"name":"geocoding.ipynb","provenance":[]}},"cells":[{"cell_type":"code","metadata":{"id":"8d8fb3af","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1639749539076,"user_tz":-330,"elapsed":3674,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}},"outputId":"625d34e9-3c70-4bc3-faa1-8d9deb344b98"},"source":["# installing geopy package\n","\n","!pip install geopy"],"id":"8d8fb3af","execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: geopy in /usr/local/lib/python3.7/dist-packages (1.17.0)\n","Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.7/dist-packages (from geopy) (1.52)\n"]}]},{"cell_type":"code","metadata":{"id":"c243d92a","executionInfo":{"status":"ok","timestamp":1639750128381,"user_tz":-330,"elapsed":417,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}}},"source":["#importing libraries\n","\n","import pandas as pd\n","from geopy.geocoders import Nominatim\n","from geopy.extra.rate_limiter import RateLimiter"],"id":"c243d92a","execution_count":2,"outputs":[]},{"cell_type":"code","metadata":{"id":"pkUYd9dmAGcH","executionInfo":{"status":"ok","timestamp":1639750154492,"user_tz":-330,"elapsed":413,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}}},"source":["df = pd.read_csv(\"geocoding1.csv\")"],"id":"pkUYd9dmAGcH","execution_count":3,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"hdVH4SrqDIWT"},"source":["# New Section"],"id":"hdVH4SrqDIWT"},{"cell_type":"code","metadata":{"id":"67b45990","executionInfo":{"status":"ok","timestamp":1639750159505,"user_tz":-330,"elapsed":404,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}}},"source":["#Creating an instance of Nominatim Class\n","geolocator = Nominatim(user_agent=\"my_request\")\n","\n","#applying the rate limiter wrapper\n","geocode = RateLimiter(geolocator.geocode, min_delay_seconds=2)\n","\n"],"id":"67b45990","execution_count":4,"outputs":[]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"da22ee5a","executionInfo":{"status":"ok","timestamp":1639751688448,"user_tz":-330,"elapsed":1494844,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}},"outputId":"22624eba-a444-4f4c-a158-f49d3b12dad3"},"source":["# applying geocode method to get locations\n","\n","df['location_geo'] = df['Location'].apply(geocode)\n"],"id":"da22ee5a","execution_count":5,"outputs":[{"output_type":"stream","name":"stderr","text":["RateLimiter caught an error, retrying (0/2 tries). Called with (*('Jakkur road',), **{}).\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 344, in _call_geocoder\n","    page = requester(req, timeout=timeout, **kwargs)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 525, in open\n","    response = self._open(req, data)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 543, in _open\n","    '_open', req)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n","    result = func(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1393, in https_open\n","    context=self._context, check_hostname=self._check_hostname)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1353, in do_open\n","    r = h.getresponse()\n","  File \"/usr/lib/python3.7/http/client.py\", line 1373, in getresponse\n","    response.begin()\n","  File \"/usr/lib/python3.7/http/client.py\", line 319, in begin\n","    version, status, reason = self._read_status()\n","  File \"/usr/lib/python3.7/http/client.py\", line 280, in _read_status\n","    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n","  File \"/usr/lib/python3.7/socket.py\", line 589, in readinto\n","    return self._sock.recv_into(b)\n","  File \"/usr/lib/python3.7/ssl.py\", line 1071, in recv_into\n","    return self.read(nbytes, buffer)\n","  File \"/usr/lib/python3.7/ssl.py\", line 929, in read\n","    return self._sslobj.read(len, buffer)\n","socket.timeout: The read operation timed out\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/extra/rate_limiter.py\", line 130, in __call__\n","    return self.func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/osm.py\", line 307, in geocode\n","    self._call_geocoder(url, timeout=timeout), exactly_one\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 371, in _call_geocoder\n","    raise GeocoderTimedOut('Service timed out')\n","geopy.exc.GeocoderTimedOut: Service timed out\n","RateLimiter caught an error, retrying (1/2 tries). Called with (*('Jakkur road',), **{}).\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 344, in _call_geocoder\n","    page = requester(req, timeout=timeout, **kwargs)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 525, in open\n","    response = self._open(req, data)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 543, in _open\n","    '_open', req)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n","    result = func(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1393, in https_open\n","    context=self._context, check_hostname=self._check_hostname)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1353, in do_open\n","    r = h.getresponse()\n","  File \"/usr/lib/python3.7/http/client.py\", line 1373, in getresponse\n","    response.begin()\n","  File \"/usr/lib/python3.7/http/client.py\", line 319, in begin\n","    version, status, reason = self._read_status()\n","  File \"/usr/lib/python3.7/http/client.py\", line 280, in _read_status\n","    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n","  File \"/usr/lib/python3.7/socket.py\", line 589, in readinto\n","    return self._sock.recv_into(b)\n","  File \"/usr/lib/python3.7/ssl.py\", line 1071, in recv_into\n","    return self.read(nbytes, buffer)\n","  File \"/usr/lib/python3.7/ssl.py\", line 929, in read\n","    return self._sslobj.read(len, buffer)\n","socket.timeout: The read operation timed out\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/extra/rate_limiter.py\", line 130, in __call__\n","    return self.func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/osm.py\", line 307, in geocode\n","    self._call_geocoder(url, timeout=timeout), exactly_one\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 371, in _call_geocoder\n","    raise GeocoderTimedOut('Service timed out')\n","geopy.exc.GeocoderTimedOut: Service timed out\n","RateLimiter swallowed an error after 2 retries. Called with (*('Jakkur road',), **{}).\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 344, in _call_geocoder\n","    page = requester(req, timeout=timeout, **kwargs)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 525, in open\n","    response = self._open(req, data)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 543, in _open\n","    '_open', req)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n","    result = func(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1393, in https_open\n","    context=self._context, check_hostname=self._check_hostname)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1353, in do_open\n","    r = h.getresponse()\n","  File \"/usr/lib/python3.7/http/client.py\", line 1373, in getresponse\n","    response.begin()\n","  File \"/usr/lib/python3.7/http/client.py\", line 319, in begin\n","    version, status, reason = self._read_status()\n","  File \"/usr/lib/python3.7/http/client.py\", line 280, in _read_status\n","    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n","  File \"/usr/lib/python3.7/socket.py\", line 589, in readinto\n","    return self._sock.recv_into(b)\n","  File \"/usr/lib/python3.7/ssl.py\", line 1071, in recv_into\n","    return self.read(nbytes, buffer)\n","  File \"/usr/lib/python3.7/ssl.py\", line 929, in read\n","    return self._sslobj.read(len, buffer)\n","socket.timeout: The read operation timed out\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/extra/rate_limiter.py\", line 130, in __call__\n","    return self.func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/osm.py\", line 307, in geocode\n","    self._call_geocoder(url, timeout=timeout), exactly_one\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 371, in _call_geocoder\n","    raise GeocoderTimedOut('Service timed out')\n","geopy.exc.GeocoderTimedOut: Service timed out\n","RateLimiter caught an error, retrying (0/2 tries). Called with (*('Subramanyapura road',), **{}).\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 344, in _call_geocoder\n","    page = requester(req, timeout=timeout, **kwargs)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 525, in open\n","    response = self._open(req, data)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 543, in _open\n","    '_open', req)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n","    result = func(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1393, in https_open\n","    context=self._context, check_hostname=self._check_hostname)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1353, in do_open\n","    r = h.getresponse()\n","  File \"/usr/lib/python3.7/http/client.py\", line 1373, in getresponse\n","    response.begin()\n","  File \"/usr/lib/python3.7/http/client.py\", line 319, in begin\n","    version, status, reason = self._read_status()\n","  File \"/usr/lib/python3.7/http/client.py\", line 280, in _read_status\n","    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n","  File \"/usr/lib/python3.7/socket.py\", line 589, in readinto\n","    return self._sock.recv_into(b)\n","  File \"/usr/lib/python3.7/ssl.py\", line 1071, in recv_into\n","    return self.read(nbytes, buffer)\n","  File \"/usr/lib/python3.7/ssl.py\", line 929, in read\n","    return self._sslobj.read(len, buffer)\n","socket.timeout: The read operation timed out\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/extra/rate_limiter.py\", line 130, in __call__\n","    return self.func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/osm.py\", line 307, in geocode\n","    self._call_geocoder(url, timeout=timeout), exactly_one\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 371, in _call_geocoder\n","    raise GeocoderTimedOut('Service timed out')\n","geopy.exc.GeocoderTimedOut: Service timed out\n","RateLimiter caught an error, retrying (1/2 tries). Called with (*('Subramanyapura road',), **{}).\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 344, in _call_geocoder\n","    page = requester(req, timeout=timeout, **kwargs)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 525, in open\n","    response = self._open(req, data)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 543, in _open\n","    '_open', req)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n","    result = func(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1393, in https_open\n","    context=self._context, check_hostname=self._check_hostname)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1353, in do_open\n","    r = h.getresponse()\n","  File \"/usr/lib/python3.7/http/client.py\", line 1373, in getresponse\n","    response.begin()\n","  File \"/usr/lib/python3.7/http/client.py\", line 319, in begin\n","    version, status, reason = self._read_status()\n","  File \"/usr/lib/python3.7/http/client.py\", line 280, in _read_status\n","    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n","  File \"/usr/lib/python3.7/socket.py\", line 589, in readinto\n","    return self._sock.recv_into(b)\n","  File \"/usr/lib/python3.7/ssl.py\", line 1071, in recv_into\n","    return self.read(nbytes, buffer)\n","  File \"/usr/lib/python3.7/ssl.py\", line 929, in read\n","    return self._sslobj.read(len, buffer)\n","socket.timeout: The read operation timed out\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/extra/rate_limiter.py\", line 130, in __call__\n","    return self.func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/osm.py\", line 307, in geocode\n","    self._call_geocoder(url, timeout=timeout), exactly_one\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 371, in _call_geocoder\n","    raise GeocoderTimedOut('Service timed out')\n","geopy.exc.GeocoderTimedOut: Service timed out\n","RateLimiter swallowed an error after 2 retries. Called with (*('Subramanyapura road',), **{}).\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 344, in _call_geocoder\n","    page = requester(req, timeout=timeout, **kwargs)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 525, in open\n","    response = self._open(req, data)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 543, in _open\n","    '_open', req)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n","    result = func(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1393, in https_open\n","    context=self._context, check_hostname=self._check_hostname)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 1353, in do_open\n","    r = h.getresponse()\n","  File \"/usr/lib/python3.7/http/client.py\", line 1373, in getresponse\n","    response.begin()\n","  File \"/usr/lib/python3.7/http/client.py\", line 319, in begin\n","    version, status, reason = self._read_status()\n","  File \"/usr/lib/python3.7/http/client.py\", line 280, in _read_status\n","    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n","  File \"/usr/lib/python3.7/socket.py\", line 589, in readinto\n","    return self._sock.recv_into(b)\n","  File \"/usr/lib/python3.7/ssl.py\", line 1071, in recv_into\n","    return self.read(nbytes, buffer)\n","  File \"/usr/lib/python3.7/ssl.py\", line 929, in read\n","    return self._sslobj.read(len, buffer)\n","socket.timeout: The read operation timed out\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/extra/rate_limiter.py\", line 130, in __call__\n","    return self.func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/osm.py\", line 307, in geocode\n","    self._call_geocoder(url, timeout=timeout), exactly_one\n","  File \"/usr/local/lib/python3.7/dist-packages/geopy/geocoders/base.py\", line 371, in _call_geocoder\n","    raise GeocoderTimedOut('Service timed out')\n","geopy.exc.GeocoderTimedOut: Service timed out\n"]}]},{"cell_type":"code","metadata":{"id":"5ee9c036","executionInfo":{"status":"ok","timestamp":1639751950993,"user_tz":-330,"elapsed":414,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}}},"source":["#Applying the method to pandas DataFrame to get Lat and Long\n","\n","df['Lat'] = df['location_geo'].apply(lambda x: x.latitude if x else None)\n","df['Lon'] = df['location_geo'].apply(lambda x: x.longitude if x else None)"],"id":"5ee9c036","execution_count":6,"outputs":[]},{"cell_type":"code","metadata":{"id":"26828a84","executionInfo":{"status":"ok","timestamp":1639751966462,"user_tz":-330,"elapsed":479,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}}},"source":["# write result to csv file\n","\n","df.to_csv(\"df_geocoded.csv\")"],"id":"26828a84","execution_count":7,"outputs":[]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"5fab932f","executionInfo":{"status":"ok","timestamp":1637759864330,"user_tz":-330,"elapsed":458,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}},"outputId":"ce31221c-0254-4a44-8b17-d2ecdbc9090e"},"source":["import geopy\n","print(geopy.geocoders.osm.Nominatim)\n"],"id":"5fab932f","execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["<class 'geopy.geocoders.osm.Nominatim'>\n"]}]},{"cell_type":"code","source":["import numpy as np"],"metadata":{"id":"e_K2n-NR6-Xl","executionInfo":{"status":"ok","timestamp":1639753470061,"user_tz":-330,"elapsed":582,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}}},"id":"e_K2n-NR6-Xl","execution_count":8,"outputs":[]},{"cell_type":"code","source":["num = np.exp(19.233+(-16.755)*2.627)\n","\n","p = num/(1+num)\n","print(p)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"IJSpcIZL7Ffu","executionInfo":{"status":"ok","timestamp":1639753678585,"user_tz":-330,"elapsed":414,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}},"outputId":"3792419e-7bf1-4132-f9c4-26b97d85c853"},"id":"IJSpcIZL7Ffu","execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["1.726421938186998e-11\n"]}]},{"cell_type":"code","source":["num1 = np.exp(19.233+(-16.755)*0.983)\n","\n","p1 = num1/(1+num1)\n","print(p1)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"KBPqI0Nn7sys","executionInfo":{"status":"ok","timestamp":1639753681964,"user_tz":-330,"elapsed":6,"user":{"displayName":"Shaurabh Anand","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjcKQGH11PNVIfS-b4W0rc3WOXljf6L6VBslXAY-A=s64","userId":"16502928129842122933"}},"outputId":"6daa2d9d-b375-4f74-d732-07433cbcd7e3"},"id":"KBPqI0Nn7sys","execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["0.940634142726724\n"]}]}]}